<a href="https://colab.research.google.com/github/Guialmeida18/Legendary-cars-api/blob/main/Projetos_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# API - E um lugar para disponilizar recursos e/ou funcionalidades

# 1. Objetivo - Criar um api que disponibiliza a consulta, criação, edição e exclusao de livros

# 2. URL base - Localhost

# 3. EndPoints -
# - localhost/livros (get)
# - localhost/livros/id (get)
# - localhost/livros/id (put)
# - localhost/livros/id (Delete)

# 4. quais recursos - livros

In [ ]:
## 1. Instalação das versões atualizadas
!pip install flask pyngrok --quiet

from flask import Flask, jsonify
from pyngrok import ngrok
import getpass

# 2. Configuração do Authtoken (Cole o token que você pegou no site)
print("Cole seu Authtoken do Ngrok abaixo:")
conf_token = getpass.getpass()
ngrok.set_auth_token(conf_token)

app = Flask(__name__)

livros = [
    {'id': 1, 'título': 'Percy Jackson e o Mar de Monstros', 'autor': 'Rick Riordan'},
    {'id': 2, 'título': 'Percy Jackson e o Ladrão de Raios', 'autor': 'Rick Riordan'},
    {'id': 3, 'título': 'Percy Jackson e a Maldição do Titã', 'autor': 'Rick Riordan'},
]
#consultar todos
@app.route('/livros', methods=['GET'])
def obter_livros():
    return jsonify(livros)

#consultar(ID)
@app.route('/livros/<int:id>', methods=['GET'])
def obter_livro_por_id(id):
    for livro in livros:
        # Se o id do livro atual for igual ao id passado na URL
        if livro.get('id') == id:
            return jsonify(livro)

# 3. Criando o túnel manualmente (o jeito que não dá erro)
try:
    # Abre o túnel na porta 5000
    public_url = ngrok.connect(5000).public_url
    print(f" * API ATIVA!")
    print(f" * Clique aqui para acessar: {public_url}/livros")

    # Roda o Flask
    app.run(port=5000)
finally:
    # Garante que o túnel fecha se você parar o código
    ngrok.kill()

Cole seu Authtoken do Ngrok abaixo:
 * API ATIVA!
 * Clique aqui para acessar: https://netherward-kaylynn-nonequivocally.ngrok-free.dev/livros
 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 14:03:24] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 14:03:24] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 14:12:52] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:35:24] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:35:57] "GET /livros/2 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:36:31] "GET /livros/%202 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:37:16] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:37:29] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:37:40] "GET /livros/1 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:37:46] "GET /livros/id2 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:38:42] "GET /livros HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:38:47] "GET /livros/id2 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:38:55] "GET /livros/2 HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [06/Apr/2026 18:39:42] "GET /livros/2 HTTP/1.1" 404 -

passo 1 - trazer minha base de dados para o python e ver o que tem nela

In [ ]:
import pandas as pd

tabela = pd.read_excel("/Vendas.xlsx")
display(tabela)

,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,2019-12-01,Iguatemi Campinas,Bermuda Estampa,1,169,169
1,2019-12-01,Iguatemi Esplanada,Bermuda Xadrez,1,155,155
2,2019-12-01,Norte Shopping,Bermuda,2,150,300
3,2019-12-01,Iguatemi Campinas,Bermuda Listrado,3,163,489
4,2019-12-01,Iguatemi Campinas,Bermuda Linho,3,195,585
5,2019-12-03,Iguatemi Campinas,Bermuda Xadrez,1,155,155
6,2019-12-03,Bourbon Shopping SP,Bermuda Listrado,1,163,163
7,2019-12-03,Bourbon Shopping SP,Bermuda Xadrez,3,155,465
8,2019-12-03,Bourbon Shopping SP,Bermuda Estampa,1,169,169
9,2019-12-04,Center Shopping Uberlândia,Bermuda Xadrez,4,155,620
10,2019-12-04,Iguatemi Esplanada,Bermuda,1,150,150
11,2019-12-04,Bourbon Shopping SP,Bermuda Estampa,2,169,338
12,2019-12-04,Iguatemi Campinas,Bermuda,4,150,600
13,2019-12-05,Iguatemi Campinas,Bermuda Liso,55,157,8635
14,2019-12-05,Iguatemi Campinas,Bermuda,4,150,600
15,2019-12-05,Bourbon Shopping SP,Bermuda Listrado,1,163,163
16,2019-12-06,Iguatemi Esplanada,Bermuda Estampa,1,169,169
17,2019-12-07,Iguatemi Campinas,Bermuda Xadrez,1,155,155
18,2019-12-07,Bourbon Shopping SP,Bermuda,3,150,450
19,2019-12-08,Center Shopping Uberlândia,Bermuda Linho,4,195,780
20,2019-12-08,Iguatemi Campinas,Bermuda Estampa,4,169,676
21,2019-12-09,Iguatemi Esplanada,Bermuda Xadrez,3,155,465
22,2019-12-10,Center Shopping Uberlândia,Bermuda Listrado,1,163,163
23,2019-12-11,Iguatemi Campinas,Bermuda Xadrez,1,155,155
24,2019-12-11,Norte Shopping,Bermuda Xadrez,2,155,310
25,2019-12-12,Iguatemi Esplanada,Bermuda Linho,1,195,195
26,2019-12-14,Bourbon Shopping SP,Bermuda Linho,1,195,195
27,2019-12-15,Iguatemi Campinas,Bermuda Linho,3,195,585
28,2019-12-15,Center Shopping Uberlândia,Bermuda Xadrez,1,155,155
29,2019-12-15,Bourbon Shopping SP,Bermuda Listrado,2,163,326
30,2019-12-16,Norte Shopping,Bermuda Listrado,1,163,163
31,2019-12-16,Bourbon Shopping SP,Bermuda Listrado,2,163,326
32,2019-12-17,Norte Shopping,Bermuda Xadrez,1,155,155
33,2019-12-17,Iguatemi Campinas,Bermuda Listrado,4,163,652
34,2019-12-17,Bourbon Shopping SP,Bermuda,2,150,300
35,2019-12-17,Bourbon Shopping SP,Bermuda Listrado,3,163,489
36,2019-12-18,Norte Shopping,Bermuda Listrado,3,163,489
37,2019-12-18,Iguatemi Esplanada,Bermuda Estampa,1,169,169
38,2019-12-19,Iguatemi Campinas,Bermuda Listrado,1,163,163
39,2019-12-19,Center Shopping Uberlândia,Bermuda Estampa,1,169,169
40,2019-12-19,Center Shopping Uberlândia,Bermuda Estampa,1,169,169
41,2019-12-19,Norte Shopping,Bermuda,1,150,150
42,2019-12-20,Bourbon Shopping SP,Bermuda Listrado,2,163,326
43,2019-12-20,Iguatemi Esplanada,Bermuda Linho,1,195,195
44,2019-12-21,Norte Shopping,Bermuda Estampa,5,169,845
45,2019-12-21,Norte Shopping,Bermuda,4,150,600
46,2019-12-21,Iguatemi Esplanada,Bermuda Linho,5,195,975
47,2019-12-22,Iguatemi Campinas,Bermuda Xadrez,1,155,155
48,2019-12-22,Center Shopping Uberlândia,Bermuda Listrado,1,163,163
49,2019-12-23,Norte Shopping,Bermuda Linho,2,195,390
50,2019-12-23,Norte Shopping,Bermuda,2,150,300
51,2019-12-24,Center Shopping Uberlândia,Bermuda Xadrez,1,155,155
52,2019-12-24,Norte Shopping,Bermuda Xadrez,4,155,620
53,2019-12-24,Center Shopping Uberlândia,Bermuda Xadrez,4,155,620
54,2019-12-24,Iguatemi Campinas,Bermuda Liso,78,157,12246
55,2019-12-25,Iguatemi Campinas,Bermuda Liso,100,157,15700
56,2019-12-26,Bourbon Shopping SP,Bermuda Estampa,4,169,676

passo 2 - pegar um panorama geral sobre a sua base de dados

In [ ]:
faturamento_total = tabela["Valor Final"].sum()
print(faturamento_total)

55895

passo 3 Começar a analsie Top -> Down

In [ ]:
# faturameto por loja
faturamento_por_loja = tabela[['ID Loja', 'Valor Final']]. groupby('ID Loja').sum()
display(faturamento_por_loja)

                            Valor Final
ID Loja
Bourbon Shopping SP                4386
Center Shopping Uberlândia         2994
Iguatemi Campinas                 41720
Iguatemi Esplanada                 2473
Norte Shopping                     4322

passo 4 entra no detalhe para entender vimos que acima o iguatemi Campinas vende mais agora qual e o causador de vender mais

In [ ]:
faturamento_por_produto = tabela[['ID Loja','Produto','Valor Final']].groupby(['ID Loja','Produto']).sum()
display(faturamento_por_produto)

                                             Valor Final
ID Loja                    Produto
Bourbon Shopping SP        Bermuda                   750
                           Bermuda Estampa          1183
                           Bermuda Linho             195
                           Bermuda Listrado         1793
                           Bermuda Xadrez            465
Center Shopping Uberlândia Bermuda Estampa           338
                           Bermuda Linho             780
                           Bermuda Listrado          326
                           Bermuda Xadrez           1550
Iguatemi Campinas          Bermuda                  1200
                           Bermuda Estampa           845
                           Bermuda Linho            1170
                           Bermuda Liso            36581
                           Bermuda Listrado         1304
                           Bermuda Xadrez            620
Iguatemi Esplanada         Bermuda                   150
                           Bermuda Estampa           338
                           Bermuda Linho            1365
                           Bermuda Xadrez            620
Norte Shopping             Bermuda                  1350
                           Bermuda Estampa           845
                           Bermuda Linho             390
                           Bermuda Listrado          652
                           Bermuda Xadrez           1085

Rodar codigo minuto a minuto

In [ ]:
import requests
import pandas as pd
from datetime import datetime
import time

while True:

  requisicao = requests.get("https://economia.awesomeapi.com.br/last/USD-BRL,EUR-BRL,BTC-BRL")

  requisicao_dic = requisicao.json()
  cotacao_dolar = requisicao_dic["USDBRL"]["bid"]
  cotacao_euro = requisicao_dic["EURBRL"]["bid"]
  cotacao_btc = requisicao_dic["BTCBRL"]["bid"]

  tabela = pd.read_excel("/Cotações.xlsx")
  tabela.loc[0, "Cotação"] = float(cotacao_dolar)
  tabela.loc[1, "Cotação"] = float(cotacao_euro)
  tabela.loc[2, "Cotação"] = float(cotacao_btc) * 1000
  tabela.loc[0, "Data Última Atualização"] = datetime.now()

  tabela.to_excel("Cotações.xlsx", index=False)
  print(f"Cotação Atualizada. {datetime.now()}")
time.sleep(60)

  # In[ ]:

KeyError: 'USDBRL'